language: node_js

node_js:
  - 10

branches:
  only:
  - master
  - develop

before_install:
  - npm install

script:
  - npm run lint
  - npm run test-coverage-coveralls
  - npm run build

cache:
  directories:
    - node_modules